version: "3.9"
services:
  build_efi:
    build: .
    working_dir: /root/edk2/
    command: bash -c "source edksetup.sh && build && cp /root/edk2/Build/MikanLoaderX64/DEBUG_CLANG38/X64/Loader.efi /root/Build/"
    volumes:
      - ./bootloader/MikanLoaderPkg/:/root/edk2/MikanLoaderPkg/
      - ./bootloader/target.txt:/root/edk2/Conf/target.txt
      - ./bootloader/Build:/root/Build/

  run_qemu:
    build: .
    command: /root/osbook/devenv/run_qemu.sh /root/mikanos/bootloader/hello.efi
    privileged: true
    volumes:
      - ~/.Xauthority:/root/.Xauthority
      - ./:/root/mikanos/
    environment:
      - DISPLAY
    network_mode: "host"