version: "3.9"
services:
  build_efi:
    build: .
    platform: linux/amd64
    working_dir: /root/edk2/
    command: bash -c "source edksetup.sh && build && cp /root/edk2/Build/MikanLoaderX64/DEBUG_CLANG38/X64/Loader.efi /root/Build/"
    volumes:
      - ./bootloader/MikanLoaderPkg/:/root/edk2/MikanLoaderPkg/
      - ./bootloader/target.txt:/root/edk2/Conf/target.txt
      - ./bootloader/Build:/root/Build/

  build_kernel:
    build: .
    platform: linux/amd64
    working_dir: /root/mikanos/kernel/
    command: bash -c "source /root/osbook/devenv/buildenv.sh && make"
    volumes:
      - ./:/root/mikanos/

  build_rkernel:
    build:
      context: .
      dockerfile: Dockerfile-rust
    working_dir: /root/mikanos/rkernel/
    command: cargo build --release
    volumes:
      - ./:/root/mikanos/

    #  VSCode + rust-analyzer + clippy + Error Lens

  run_qemu:
    build:
      context: .
      dockerfile: Dockerfile-qemu
    command: /root/osbook/devenv/run_qemu.sh bootloader/Build/Loader.efi kernel/kernel.elf
    working_dir: /root/mikanos/
    privileged: true
    volumes:
      - ~/.Xauthority:/root/.Xauthority
      - ./:/root/mikanos/
    environment:
      - DISPLAY
    network_mode: "host"

  run_rqemu:
    build:
      context: .
      dockerfile: Dockerfile-qemu
    command: /root/osbook/devenv/run_qemu.sh bootloader/Build/Loader.efi rkernel/target/x86_64-unknown-none/release/kernel.elf
    working_dir: /root/mikanos/
    privileged: true
    volumes:
      - ~/.Xauthority:/root/.Xauthority
      - ./:/root/mikanos/
    environment:
      - DISPLAY
    network_mode: "host"
