version: "3.9"
services:
  build_efi:
    build: .
    working_dir: /root/mikanos/bootloader
    command: make
    volumes:
      - ./:/root/mikanos/

  run_qemu:
    build: .
    command: /root/osbook/devenv/run_qemu.sh /root/mikanos/bootloader/hello.efi
    privileged: true
    volumes:
      - ~/.Xauthority:/root/.Xauthority
      - ./:/root/mikanos/
    environment:
      - DISPLAY
    network_mode: "host"