[build]
target = "x86_64-unknown-none.json"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-unknown-none]
# runner = "qemu-system-x86_64"
rustflags = [
  "-C",
  "link-arg=--image-base=0x100000",
]
